export const imagesToLoad = [
    "/game/coin_big.png",
    "/game/coin.png",
    "/svg/yes.svg",
    "/svg/next.svg",
    "/raffle/background.png",
    "/game/giftbox.png",
    "/game/Boost_Big.png",
    "/svg/copy.svg",
    "/icon/close.svg",
    "/icon/invitetab.png",
    "/icon/addfriend.png",
    "/icon/friendrequest.png",
    "/icon/friendsearch.png",
    "/game/Farmed.png",
    "/game/Default.png",
    "/game/Notowned.png",
    "/game/record.png",
    "/game/collap.png",
    "/game/combineicon.png",
    "/game/energyicon.png",
    "/game/stealicon.png",
    "/game/watericon.png",
    "/game/radar.png",
    "/game/record.png",
    "/crop/Wheat_0.png",
    "/crop/Wheat_7.png",
    "/game/seeding.png",
    "/game/harvesting.png",
    "/game/success-banner.png",
    "/game/watering.png",
    "/game/background_new.png",
    "/game/raffle.png",
    "/game/blueberry-icon.png",
    "/game/crown.png",
    "/game/Farm_token.png",
    "/game/leaderboard-popup-bg.png",
    "/game/reward-box-background.png",
    "/game/view-leaderboard-button.png",
    "/raffle/pointer.png",
    "/raffle/unlucky.png",
    "/raffle/winner.png",
    "/game/market.png",
    "/game/wallet-banner.png",
    "/game/wallet banner.png",
    "/game/Onboarding-earn.png",
    "/game/combine_rewards.png",
    "/game/Onboarding-Upgrade.png",
    "/game/boostbackground.png",
    "/game/success-container.png",
    "/game/onBoarding1.png",
    "/game/market.png",
    "/artela.png",
    "/svg/walletPfp.svg",
    "/icon/earntab.png",
    "/icon/farmtab.png",
    "/icon/friendstab.png",
    "/icon/wallettab.png",
    "/wallet/pic_wallet.png",
]

export function preloadImage(src: string) {
    return new Promise((resolve, reject) => {
        const img = new Image()
        img.onload = () => resolve(img)
        img.onerror = (err) => reject(err)
        img.src = src
    })
}
