export const messages = [
    "Your [crop] is thriving.",
    "The [crop] is looking great.",
    "Your [crop] is growing strong.",
    "The [crop] is progressing well.",
    "Your [crop] is in good condition.",
    "The [crop] is developing as expected.",
    "Your [crop] shows no signs of issues.",
    "The [crop] is flourishing.",
    "Your [crop] is doing just fine.",
    "The [crop]'s growth is reassuring.",
    "Your [crop] is showing promising growth.",
    "The [crop] is coming along nicely.",
    "Your [crop] is developing healthily.",
    "The [crop]'s condition is satisfactory.",
    "Your [crop] is free from any problems.",
    "The [crop] is growing at a good pace.",
    "Your [crop] looks vigorous.",
    "The [crop] is in excellent shape.",
    "Your [crop] is meeting all expectations.",
    "The [crop] is thriving in your care.",
    "Your [crop] is showing robust growth.",
    "The [crop] appears to be in top form.",
    "Your [crop] is progressing smoothly.",
    "The [crop] is developing beautifully.",
    "Your [crop] is in prime condition.",
    "The [crop] is growing steadily.",
    "Your [crop] looks very healthy.",
    "The [crop] is coming up strong.",
    "Your [crop] is right on track.",
    "The [crop] is growing like a champ.",
    "Your [crop] is doing splendidly.",
    "The [crop] is in tip-top shape.",
]
